name: python_calculator

on:
  push:
    branches: [ "main" ]

jobs:
  buil-and-test:
    runs-on: ubuntu-latest

    steps:
      #Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      #Step 2: set up python
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      #Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      #Step 4: Run test
      - name: Run Tests
        run: pytest ./test_calculator.py -v

      #Step 5: Upload test report as artifact
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml